name: CI Workflow

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Pakai ABSOLUTE PATH ke mlruns agar tidak “nyasar” antar proses
      MLFLOW_TRACKING_URI: file:${{ github.workspace }}/Workflow-CI/MLProject/mlruns
      MLFLOW_EXPERIMENT_NAME: CI-Workflow

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0 catboost==1.2.5 scikit-learn==1.5.2 pandas==2.2.3 numpy==1.26.4 matplotlib==3.9.2 scipy==1.11.4

      - name: Ensure tracking dir exists
        run: |
          mkdir -p "${{ github.workspace }}/Workflow-CI/MLProject/mlruns"

      - name: Run MLflow Project
        working-directory: Workflow-CI/MLProject
        env:
          # pastikan env yang sama juga masuk ke step ini
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: |
          mlflow run . --env-manager=local --experiment-name "${MLFLOW_EXPERIMENT_NAME}"

      - name: Capture latest run_id (by experiment name)
        working-directory: Workflow-CI/MLProject
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
          MLFLOW_EXPERIMENT_NAME: ${{ env.MLFLOW_EXPERIMENT_NAME }}
        run: |
          EXPT_ID=$(mlflow experiments list --view-all | awk -v name="${MLFLOW_EXPERIMENT_NAME}" '$0 ~ name {print $1}')
          echo "Experiment ID: $EXPT_ID"
          RUN_ID=$(mlflow runs list --experiment-id "$EXPT_ID" --max-results 1 --order-by attributes.start_time DESC | awk 'NR==2{print $1}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest run_id: $RUN_ID"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: |
            Workflow-CI/MLProject/mlruns/
            Workflow-CI/MLProject/submission.csv
            Workflow-CI/MLProject/confusion_matrix_val.png
            Workflow-CI/MLProject/feature_importance.csv

      - name: Commit & Push results (optional)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Workflow-CI/MLProject/mlruns/ || true
          git commit -m "Upload MLflow artifacts [skip ci]" || echo "No changes to commit"
          git push origin main || true

      - name: Build Docker Image from MLflow model
        if: env.RUN_ID != ''
        working-directory: Workflow-CI/MLProject
        env:
          MLFLOW_TRACKING_URI: ${{ env.MLFLOW_TRACKING_URI }}
        run: |
          mlflow models build-docker --model-uri "runs:/${{ env.RUN_ID }}/model" --name creditscore_model

      - name: Login to Docker Hub
        if: env.RUN_ID != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Tag & Push Docker Image
        if: env.RUN_ID != ''
        run: |
          docker tag creditscore_model ${{ secrets.DOCKER_HUB_USERNAME }}/creditscore_model:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/creditscore_model:latest
